version: '3.9'
services:
  backend:
    build: .
    port:
      - 8000:3000
    volumes:
      . /: app
    depends_on: -db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: postgres
      POSTGRES_POST: 5060
      POSTGRES_PASWWORD: root
      POSTGRES_ROOT_PASWWORD: root
    volumes:
      - .dbdata: /var/lib/postgres
